### ISSUE TITLE
Chests Render Incorrectly

### ISSUE THREAD

**Issue by Sunsprint** [MushirMickeyJoe/Relatively-Improved-Default#48] opened 2020-04-12 18:20 UTC
Chests, ~~double chests~~, trapped chests and ender chests all render with the top lid texture reversed with the bottom lid texture. This is not an issue with the item form of minecart chests.

EDIT: Double chests do not have this problem.

**Comment by MushirMickeyJoe** [comment] 2020-05-25 23:33
Duplicate of #7

**Closed as completed by MushirMickeyJoe** 2020-05-25 23:33 UTC
